server:
  port: 8089
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/study-article
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  #mapper文件的路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
user:
  id: 4
  userName: 锖青磁